FROM python:3.12-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential git ffmpeg libsm6 libxext6 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Clone the rainbow tables
RUN git clone https://github.com/inAudible-NG/tables.git /app/audible_rainbow_tables

COPY . .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]